### ISSUE TITLE
Replace/remove images to follow Alpine Linux official releases

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/alpine-erlang#2]
I'll replace/remove some of the Erlang/Elixir images available on Docker Hub. The reason is that all the images that depend on the `apk` packages will now follow the official releases from Alpine Linux. That means after the release of the upcoming AL version 3.3, there will be only two versions of erlang, "18.1"(latest) and "edge". All newer versions will replace the "edge" version until the next release of AL and then the erlang version gets "frozen" among the the AL version. After this change there will be only the following images available:
- msaraiva/erlang:18.1 (latest)
- msaraiva/erlang:edge 
- msaraiva/elixir:1.1.1 (based on msaraiva/erlang:18.1)
- msaraiva/elixir-dev:1.1.1 (based on msaraiva/erlang:18.1)
- And any other future version of elixir that depends on msaraiva/erlang:18.1

All other images will be removed.

For Elixir versions that might, in the future, depend on newer releases of Erlang, we could also have:
- msaraiva/elixir:edge (based on msaraiva/erlang:edge)
- msaraiva/elixir-dev:edge (based on msaraiva/erlang:edge)

This way we can avoid conflicts and instability since we ensure that all releases, except the ones tagged as "edge", will always depend on the same `apk` package.

Cheers!
-marlus

**Comment by nenros** [comment]
Thank you, I tried to search docker image with actual erlang/elixir yesterday, and because I didn't find nothing with that requirement I tried to create something on my own, it took me all evening and of course I didn't  create it at all.
So have you got any estimated time when you will publish them, and can I help you in something?

**Comment by msaraiva** [comment]
@nenros we expect to have Alpine Linux v3.3 very soon as you can see [here](https://github.com/msaraiva/alpine-erlang/issues/3#issuecomment-154821002). As soon as it is released I'll update the images as proposed.

**Comment by ncopa** [comment]
elixir and erlang should now be available from v3.3/community repo.

**Comment by msaraiva** [comment]
Great! I'll update the images over the weekend. 

@ncopa Thanks for your great work. Alpine Linux is just awesome.

**Comment by msaraiva** [comment]
The official `alpine` image at docker hub hasn't been updated to v3.3 yet. So I guess I'll wait a few days until we have the 3.3 tag.

**Comment by msaraiva** [comment]
Images updated.
